### ISSUE TITLE
find_by_sql with UPDATE performed on read-only slave

### ISSUE THREAD

**Issue by jacob-s-son** [tchandy/octopus#157]
Hi, guys!

Ran into problem with delayed_job_active_record, particulartly this query is executed on read-only slave:

```ruby
self.find_by_sql(["UPDATE #{quotedTableName} SET locked_at = ?, locked_by = ? WHERE id IN (#{nextScope.to_sql}) RETURNING *",now,worker.name])
```
Since had no response at delayed_job repo, maybe You are willing to comment could it be an Octopus issue (maybe ActiveRecord's ?).

Issue in delayed_job repo:
https://github.com/collectiveidea/delayed_job_active_record/issues/34

**Comment by sobrinho** [comment]
Closing due to lack of movement but I would be happy to merge, just mention this issue on the PR.
