### ISSUE TITLE
before_add/before_remove options in Octopus::Association

### ISSUE THREAD

**Issue by lawrencepit** [tchandy/octopus#169]
Just reading the code, noticed this in Octopus::Association:

```ruby
  def default_octopus_opts(options)
    if options[:before_add].is_a?(Array)
      options[:before_add] << :set_connection_on_association
    elsif options[:before_add].is_a?(Symbol)
      options[:before_add] = [:set_connection_on_association, options[:before_add]]
```

I assume `set_connection_on_association` should be inserted in front of the array instead of pushed to the end, just like it's done when the option value is a Symbol ?

I didn't see any tests/specs for this code.

**Comment by tchandy** [comment]
Hi @lawrencepit ,

It was fixed on Octopus master. 

I'm going to close your issue. If you have any additional problems please feel free to reopen.

Thiago
