### ISSUE TITLE
Octopus.using not working out of the box?

### ISSUE THREAD

**Issue by lawrencepit** [tchandy/octopus#170]
I was using this piece of code as documented in the [README](https://github.com/tchandy/octopus) :

```ruby
  around_filter :select_shard
  def select_shard(&block)
    Octopus.using(:brazil, &block)
  end
```

but it was reading everything from the master database.

after digging around the octopus code found I had to do:

```ruby
  around_filter :select_shard
  def select_shard(&block)
    ActiveRecord::Base.custom_octopus_connection = false
    Octopus.using(:brazil, &block)
  end
```

Is that how it's intended to work, or was I missing something obvious?

**Comment by sobrinho** [comment]
Closing due to lack of movement but I would be happy to inspect if this is still an issue for you. Please test against latest released version if that's the case.
