### ISSUE TITLE
Configuration Option to Disable Migrations on Slaves

### ISSUE THREAD

**Issue by kplawver** [tchandy/octopus#180]
If my database is replicated, then I shouldn't need to run migrations on it.  

I tried setting up ar-octopus on an existing app and even though the schema_migrations tables were identical on both the master and slave, it tried to apply *all* the migrations to the slave.  I've looked through the code and don't see an easy way to force migrations only to run on the master for simple master/slave setups.

Thanks!

**Comment by tchandy** [comment]
Thanks for your answer @joetastic .

Closing this issue.
