### ISSUE TITLE
How to change pool size

### ISSUE THREAD

**Issue by rainerborene** [tchandy/octopus#184]
How can I change the database pool size in the Sidekiq "environment"? I'm getting lots of `ActiveRecord::ConnectionTimeoutError`: could not obtain a database connection within 5 seconds.

**Comment by tchandy** [comment]
HI @rainerborene , 

There is an article about how to use Octopus with heroku on our wiki: https://github.com/tchandy/octopus/wiki/Replication-with-Rails-on-Heroku

I'm closing this issue. If you have any additional problems, please feel free to reopen.

Thiago
