### ISSUE TITLE
Octopus accessing DEV database on unit tests

### ISSUE THREAD

**Issue by HenleyChiu** [tchandy/octopus#185]
When I run rake tests, octopus seems to connect to my development database, even though I have no shards setup in test.

Here's my shards.yml
octopus:
  environments:
    - development
  development:
    shard_one:
        adapter: postgresql
        encoding: unicode
        database: buzzsumo
        host: 192.168.1.115
        pool: <%= ENV['DB_POOL'] %>
        username: postgres
        password: BLAHBLAH
        reconnect: true
    shard_two:
        adapter: postgresql
        encoding: unicode
        database: buzzsumo
        host: localhost
        pool: 5
        username: postgres
        password: BLAHBLAH
        reconnect: true

**Comment by sobrinho** [comment]
Closing due to lack of movement but I would be happy to inspect if this is still an issue for you. Please test against latest released version if that's the case.
