### ISSUE TITLE
Conflicts between Heroku postgis configuration with unicorn and octopus.

### ISSUE THREAD

**Issue by michaltn** [tchandy/octopus#202]
Hey I am trying to set up octopus to do a bit of db sharding unfortunately as soon as I add the gem my application stops seeing its db connection.

I tracked it down to this piece of code in unicorn.rb

before_fork do |server, worker|
  defined?(ActiveRecord::Base) and ActiveRecord::Base.connection.disconnect!
  defined?(Resque) and Resque.redis.quit
end  

after_fork do |server, worker|
  if defined?(ActiveRecord::Base) && defined?(ActiveSupport)
    ActiveSupport.on_load(:active_record) do
      cfg = Rails.application.config.database_configuration[Rails.env]
      cfg['adapter'] = 'postgis'
      ActiveRecord::Base.establish_connection(cfg)
      Admin::ProposedLocation.using(:avail_reports_shard).reset_column_information
    end
  end
end

We drop the connection in before fork and try to reestablish it with a postgis addpater after fork. This is a recommended way to configure postgis with heroku and their support fail to recommend an alternative.

However I dont think this new connection will properly propagate to the proxy leading all sorts of havoc. 

I tried experimenting with octopus_establish_connection but this will kill my ability to access the shard (that is configured with postgis adapter in shards.yml).

A little help would be greatly appreciated. How do I get this to work ?

**Comment by sobrinho** [comment]
I'm not sure it's up to octopus deal with postgis + unicorn but I see your pain.

I would recommend a threaded server like puma instead of trying to workaround that :)
