### ISSUE TITLE
"using" method inside another method in model

### ISSUE THREAD

**Issue by noff** [tchandy/octopus#203]
Hello. Have different shards and tables for one big list of elements.
Trying to simplify method of reading rows from shards.

Trying to use this construction

`links = Link.set_table_for_user(user_id).where(user_id: user_id)`

In model:
```
class Link < ActiveRecord::Base

  def self.set_table_for_user(user_id)
    using(get_shard_name_by_user_id user_id)
    self.table_name = Link.get_table_name_by_user_id(user_id)
    self.all
  end

  def self.get_table_name_by_user_id(user_id)
    n = '%02d' % (user_id.to_s.slice(0,10).to_i(16)%100) # transform '1' to '01'
    return "link_texts_#{n}"
  end

end
```

So, block `using` inside of method is not works. Octopus trying to find rows in :master shard, not calculated shard.

It works if I write:
```
shard = Link.get_shard_name_by_user_id(user_id)
Link.using(shard).set_table_for_user(user_id).where(user_id: user_id)
```

Any method to use "using" inside static method of model?

**Comment by sobrinho** [comment]
You probably made a mistake on set_table_for_user, you should return the using scope:

``` ruby
class Link < ActiveRecord::Base

  def self.set_table_for_user(user_id)
    self.table_name = Link.get_table_name_by_user_id(user_id)
    self.all
    using(get_shard_name_by_user_id user_id)
  end

  def self.get_table_name_by_user_id(user_id)
    n = '%02d' % (user_id.to_s.slice(0,10).to_i(16)%100) # transform '1' to '01'
    return "link_texts_#{n}"
  end

end
```

Feel free to reopen if this is still an issue on latest release.
