### ISSUE TITLE
Is there a way to mark a Slave as being blacklisted?

### ISSUE THREAD

**Issue by AaronRustad** [tchandy/octopus#204]
I understand that Octopus doesn't support automatic Failover, but when an exception is raised from a slave, is there a way I can programatically remove that connection from the pool?

If I have two slave and on goes down, I'm seeing Octopus hit the downed slave 50% of the time. I'd like to remove it.

Thanks!
AR

**Comment by sobrinho** [comment]
I created #323 to discuss about that.
