### ISSUE TITLE
Octopus and ActionController::Live

### ISSUE THREAD

**Issue by evgenylivensky** [tchandy/octopus#206]
Hello everyone!

When I add new controller in my app using ActionController::Live my app freezes and then an error:

    could not obtain a database connection within 5.000 seconds (waited 5.001 seconds).

If turn off octopus gem, added controller working as it should.

	ActiveRecord::ConnectionTimeoutError (could not obtain a database connection within 5.000 seconds (waited 5.001 seconds)):
	  activerecord (4.0.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:190:in `block in wait_poll'
	  activerecord (4.0.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:181:in `loop'
	  activerecord (4.0.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:181:in `wait_poll'
	  activerecord (4.0.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:136:in `block in poll'
	  /usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
	  activerecord (4.0.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:146:in `synchronize'
	  activerecord (4.0.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:134:in `poll'
	  activerecord (4.0.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:423:in `acquire_connection'
	  activerecord (4.0.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:356:in `block in checkout'
	  /usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
	  activerecord (4.0.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:355:in `checkout'
	  activerecord (4.0.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:265:in `block in connection'
	  /usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
	  activerecord (4.0.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:264:in `connection'
	  /home/evg/.bundler/ruby/1.9.1/octopus-b67afb161ef3/lib/octopus/proxy.rb:143:in `safe_connection'
	  /home/evg/.bundler/ruby/1.9.1/octopus-b67afb161ef3/lib/octopus/proxy.rb:234:in `block in clear_all_query_caches!'
	  /home/evg/.bundler/ruby/1.9.1/octopus-b67afb161ef3/lib/octopus/proxy.rb:234:in `each'
	  /home/evg/.bundler/ruby/1.9.1/octopus-b67afb161ef3/lib/octopus/proxy.rb:234:in `clear_all_query_caches!'
	  /home/evg/.bundler/ruby/1.9.1/octopus-b67afb161ef3/lib/octopus/rails3/abstract_adapter.rb:45:in `clear_query_cache_with_octopus'
	  /home/evg/.bundler/ruby/1.9.1/octopus-b67afb161ef3/lib/octopus/proxy.rb:209:in `method_missing'
	  activerecord (4.0.0) lib/active_record/query_cache.rb:51:in `restore_query_cache_settings'
	  activerecord (4.0.0) lib/active_record/query_cache.rb:43:in `rescue in call'
	  activerecord (4.0.0) lib/active_record/query_cache.rb:32:in `call'
	  activerecord (4.0.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
	  activerecord (4.0.0) lib/active_record/migration.rb:369:in `call'
	  actionpack (4.0.0) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
	  activesupport (4.0.0) lib/active_support/callbacks.rb:373:in `_run__871106874__call__callbacks'
	  activesupport (4.0.0) lib/active_support/callbacks.rb:80:in `run_callbacks'
	  actionpack (4.0.0) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
	  actionpack (4.0.0) lib/action_dispatch/middleware/reloader.rb:64:in `call'
	  actionpack (4.0.0) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
	  actionpack (4.0.0) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
	  actionpack (4.0.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
	  railties (4.0.0) lib/rails/rack/logger.rb:38:in `call_app'
	  railties (4.0.0) lib/rails/rack/logger.rb:21:in `block in call'
	  activesupport (4.0.0) lib/active_support/tagged_logging.rb:67:in `block in tagged'
	  activesupport (4.0.0) lib/active_support/tagged_logging.rb:25:in `tagged'
	  activesupport (4.0.0) lib/active_support/tagged_logging.rb:67:in `tagged'
	  railties (4.0.0) lib/rails/rack/logger.rb:21:in `call'
	  actionpack (4.0.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
	  rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
	  rack (1.5.2) lib/rack/runtime.rb:17:in `call'
	  activesupport (4.0.0) lib/active_support/cache/strategy/local_cache.rb:83:in `call'
	  actionpack (4.0.0) lib/action_dispatch/middleware/static.rb:64:in `call'
	  railties (4.0.0) lib/rails/engine.rb:511:in `call'
	  railties (4.0.0) lib/rails/application.rb:97:in `call'
	  rack (1.5.2) lib/rack/content_length.rb:14:in `call'
	  puma (2.6.0) lib/puma/server.rb:486:in `handle_request'
	  puma (2.6.0) lib/puma/server.rb:357:in `process_client'
	  puma (2.6.0) lib/puma/server.rb:250:in `block in run'
	  puma (2.6.0) lib/puma/thread_pool.rb:92:in `call'
	  puma (2.6.0) lib/puma/thread_pool.rb:92:in `block in spawn_thread'

Controller

	require 'sse/writer'
	class RealtimeController < ApplicationController
	  
	  include ActionController::Live

	  before_action :setup_stream

	  def comments
	    begin
	      @redis.subscribe('new_comment') do |on|
		on.message do |event, data|
		  @stream.write(JSON.parse(data).to_json, :event => :new)
		end
	      end
	    ensure
	      @stream.close
	    end
	  end

	  private

	  def setup_stream
	    response.headers['Content-Type'] = 'text/event-stream'
	    @redis  = Redis.new
	    @stream = Sse::Writer.new(response.stream)
	  end

	end

sse/writer.rb

	module Sse
	  class Writer
	    def initialize io
	      @io = io
	    end

	    def write object, options = {}
	      
	      options.each do |k,v|
		@io.write "#{k}: #{v}\n"
	      end

	      @io.write "data: #{object}\n\n"
	    end

	    def close
	      @io.close
	    end
	  end
	end

**Comment by sobrinho** [comment]
This error means you have less connections on pool than you need.

I can see on the backtrace that you are using puma, which defaults to 16 threads whereas rails defaults the pool size of 5 connections.

Feel free to reopen if this is still an issue on latest release with connection pool configured accordingly.
