### ISSUE TITLE
using octopus with plain ruby - establish_connection

### ISSUE THREAD

**Issue by seoaqua** [tchandy/octopus#209]
this could work:
```ruby
require 'active_record'
require 'ar-octopus'
@db = {'host'=>''...............}
ActiveRecord::Base.establish_connection($db)
class User < ActiveRecord::Base
end

User.take

```

how to make this work?

```ruby
require 'active_record'
require 'ar-octopus'
@db = {'host'=>''...............}

class User < ActiveRecord::Base
    establish_connection($db)
end

User.take

```

the problem is located at proxy.rb line 15

```ruby
@shards[:master] = ActiveRecord::Base.connection_pool()
```

by watching connection_pool.rb line 579
octopus is looking for "ActiveRecord::Base" in @class_to_pool

 does this mean one project can only have one master connection config?
what if i need 2 masters : a_master, b_master
and 4 slaves: a_slave_1, a_slave_2, b_slave_1, b_slave2

**Comment by tchandy** [comment]
Hi @seoaqua ,

Yes, the project can have only one master. All other databases should be specified as shards in the shards.yml file. 

I'm closing this issue. If you have any additional problems, please feel free to reopen.

Thiago
