### ISSUE TITLE
using octopus with plain ruby - config

### ISSUE THREAD

**Issue by seoaqua** [tchandy/octopus#210]
cuz i need an internal GEM for my team. i have to hack Octopus.
are there any better ways?

```ruby
require 'active_record'
require 'ar-octopus'

module Octopus
  def self.config=(config)
    @config = config
  end
end
Octopus.config = {
         "replicated" => true,
    "full_replicated" => true,
             "shards" => {
        "slave1" => {
             "adapter" => "mysql2",
                "host" => "host1",
            "database" => "xxx",
            "username" => "xxx",
            "password" => "xxx"
        },
        "slave2" => {
             "adapter" => "mysql2",
                "host" => "host2",
            "database" => "xxx",
            "username" => "xxx",
            "password" => "xxx"
        }
    }
}

ActiveRecord::Base.establish_connection($db)
class User < ActiveRecord::Base
end

User.take
```

**Comment by tchandy** [comment]
Hi @seoaqua ,

You don't need to create the config= method on Octopus. You could just an config directory, and put the shards.yml file there.

I'm closing this issue, if you have any additional problems please feel free to reopen.

Thiago

**Comment by seoaqua** [comment]
sometimes you can't create that config file. for my team the database gem using Octopus is a standalone project and it's included by many other projects. anyway, maybe this is a wrong way:)
