### ISSUE TITLE
How to get raw shard db connection?

### ISSUE THREAD

**Issue by HenleyChiu** [tchandy/octopus#216]
How do I get a connection for a particular shard?

I tried:
Octopus.using(:new_db) do   
            connection = ActiveRecord::Base.connection
end

But it gives me the connection for the default db connection for production as specified in my database.yml, not the shard "new_db" as specified in my shards.yml.

**Comment by tchandy** [comment]
Hi @HenleyChiu,

Since @mumoshu comment solved your problem, I'm closing this issue.

Thiago
