### ISSUE TITLE
octopus_establish_connection not working with Inherited class

### ISSUE THREAD

**Issue by chmadhu13** [tchandy/octopus#219]
Hi,

I have 2 classes as follows

class A  < ActiveRecord::Base
  self.abstract_class = true
  octopus_establish_connection("non_default_db")
end

class B < A
end

If I look at A.connection_config it gives me proper result connected to non_default_db connection configuration. But B.connection_config gives me the result of default development connection instead of non_default_db connection configuration.

Here is the result
A.connection_config result => {:adapter=>"mysql2", :encoding=>"utf8", :reconnect=>true, :database=>"development", :pool=>5, :username=>"root", :password=>"123", :host=>"localhost"}

B.connection_config result => {:adapter=>"mysql2", :encoding=>"utf8", :reconnect=>true, :database=>"non_default_development", :pool=>5, :username=>"root", :password=>"123", :host=>"localhost", :flags=>2}

Could you please tell me what the reason could be and how to fix this issue.

**Comment by britg** [comment]
Has anyone had luck with this issue? We're running into the same thing: calling 'octopus_establish_connection' is creating a new connection for every model that does this, but using the 'abstract_model' method does not actually create the connection.

**Comment by verlinden** [comment]
Hi, I have the same issue. I was using establish_connection in an abstract model and had several models who inherited from that class, it worked fine.
I'm now switching to octopus but the "octopus_establish_connection" doesn't work in an abstract model.

**Comment by verlinden** [comment]
The best working workaround is this one

````ruby
def self.inherited(child)
  child.octopus_establish_connection Octopus.config[Rails.env][:your_shard]
  super
end
````

**Comment by juanpastas** [comment]
@markoblad I suppose you can do something like:

```
 def self.inherited(child)
    @child_connections ||= {}
    @child_connections[shard_name] ||= child.octopus_establish_connection Octopus.config[Rails.env][shard_name]
    super
  end
```

**Comment by markoblad** [comment]
Many thanks @juanpastas.  I'll give that a try.

**Comment by mihirg** [comment]
@juanpastas can you explain the logic behind your proposed solution?

**Comment by juanpastas** [comment]
@mihirg from what I remember it was to make each children class to use parent connection settings. I don't remember details. In my second code, which I ave not tested, connections are cached in order to limit the number of connections.

**Comment by sobrinho** [comment]
I can reproduce this issue, working on a fix right now.

**Comment by sobrinho** [comment]
Can you check 68f1da81fab2dd48f7ef361cac745dea648af371 fixes the problem for you?

If nothing goes wrong on next couple days, I will cherry-pick it on master.

**Comment by zhuochun** [comment]
I tested your fix works. Will you merge to master and release a newer version soon? :smile:

**Comment by althafh** [comment]
I'm actually interested in this fix as well!

**Comment by rlhh** [comment]
:+1: to the fix

**Comment by sobrinho** [comment]
Nice, I will merge it ASAP and release a new version, probably in 8 hours (the day has just begun here).

**Comment by xinan** [comment]
:+1: Great! Thanks!

**Comment by zhuochun** [comment]
Thanks :tada:

**Comment by sobrinho** [comment]
It's on master but the build is broken, I'm looking into it.

**Comment by sobrinho** [comment]
Fixed, feel free to use master version while we build a new release :)

**Comment by althafh** [comment]
Thank you!
