### ISSUE TITLE
adding replicated_model causes my controller tests to fail

### ISSUE THREAD

**Issue by smooshy** [tchandy/octopus#222]
I've just installed octopus to my app and adding replicated_model causes some issues with my specs. 

Relevant lines of code:
```
    let!(:chart) { create(:chart, displayer: page) }
    it "sets a flash message" do
      delete :destroy, id: chart
      ...
    end
```

If I break right before the delete command, I can see that chart is created in memory and has a valid id:
```
(rdb:1) chart
#<PieChart id: 1, created_at: "2014-02-04 19:27:22",...
```

Log in test.log:
```
  (0.4ms)  SAVEPOINT active_record_1
  Chart Load (1.0ms)  SELECT "charts".* FROM "charts" WHERE (charts.position IS NOT NULL) AND ("charts"."displayer_id" = 1) ORDER BY charts.position DESC LIMIT 1
  SQL (1.5ms)  INSERT INTO "charts" ("created_at", "displayer_id", "displayer_type", "metric_type", "options", "position", "title", "tracker_filters", "tracking_years", "type", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) RETURNING "id"  [["created_at", Tue, 04 Feb 2014 19:27:22 UTC +00:00], ["displayer_id", 1], ["displayer_type", "Node"], ["metric_type", "energy"], ["options", nil], ["position", 1], ["title", "Chart Wooo"], ["tracker_filters", nil], ["tracking_years", "---\n- 0\n"], ["type", "PieChart"], ["updated_at", Tue, 04 Feb 2014 19:27:22 UTC +00:00]]
   (0.2ms)  RELEASE SAVEPOINT active_record_1
```

However, the call to find the chart in the #delete action fails as it can't find the chart in the database. In the debugger:
```
(rdb:1) Chart.find(chart.id)
*** ActiveRecord::RecordNotFound Exception: Couldn't find Chart with id=1

(rdb:1) Chart.all
#<ActiveRecord::Relation []>
(rdb:1)
```

So it appears that the model created by FactoryGirl is not actually writing the model to the database? Am I missing some configuration options? Is there a compatibility issue with some of the gems I'm using? Anyone else have this issue? 

Gems: 
```
rails (4.0.2)
rspec (2.14.1)
ar-octopus (0.8.0)
database_cleaner (1.2.0)
factory_girl (4.3.0) - thoughtbot version'
...
```

I'm using the shards.yml that others have posted for running octopus on heroku at https://gist.github.com/eprothro/5374472 and octopus.rb at https://gist.github.com/eprothro/5374500

**Comment by sobrinho** [comment]
If you are using `replicated_model` and create the record on master, the next find will query it on slave, which will probably be not there.

I personally prefer to disable octopus on test environment since it's not important for me and makes a lot of work to replication work (you need to insert on master and every slaves).

If you would like to keep it enabled on test environment, you need to insert on slaves like this:

``` ruby
let!(:chart) do
  Octopus.using(:slave1) { create(:chart, displayer: page) }
  Octopus.using(:slave2) { create(:chart, displayer: page) }

  create(:chart, displayer: page)
end
```

Don't forget if page is also on  a replicated model, you need to do the same thing for it, that's what mean with lot of work :)
