### ISSUE TITLE
unable to create geometry with octopus

### ISSUE THREAD

**Issue by innovia** [tchandy/octopus#223]
ActiveRecord::StatementInvalid (Mysql2::Error: Cannot get geometry object from data you send to the GEOMETRY field: INSERT INTO `areas` (`borders`, `centroid_lat`, `centroid_lon`, `coordinates`, `created_at`, `is_airport`, `is_deleted`, `is_delivery`, `polygon`, `ref_point_lat`, `ref_point_lon`, `size`, `state_id`, `title`, `updated_at`) VALUES ('POLYGON((32.1408433928894 34.93105173110962,32.140916069386314 34.93272542953491,32.139607883580034 34.932682514190674,32.13942618962277 34.93126630783081,32.1408433928894 34.93105173110962))', 32.14019838386963, 34.9319314956665, NULL, '2014-02-05 16:05:24', 0, 0, 0, '32.1408433928894,34.93105173110962_32.140916069386314,34.93272542953491_32.139607883580034,34.932682514190674_32.13942618962277,34.93126630783081_', NULL, NULL, 22205.303834454462, NULL, 'נסיון_עמי', '2014-02-05 16:05:24')):

this does not happen on a server that does not use octopus

the setup we have is sharding regular spilt read write  for reports server only

**Comment by tchandy** [comment]
Hi @innovia ,

Could you provide an failing test case?

Thiago

**Comment by innovia** [comment]
Hi Thiago 

I'm gonna close this ticket, I do not work there anymore and can;t remember the scenario

Thanks any way

Ami
