### ISSUE TITLE
octopus_establish_connection not working when opening a Class

### ISSUE THREAD

**Issue by juanpastas** [tchandy/octopus#231]
I am using `paper_trail` gem to track changes in my records, my question is explained [here](http://stackoverflow.com/questions/22051287/papertrail-and-octopus-specify-connection-for-versions-table).

Here is a copy:

So far I can do this in console to make it work:

    PaperTrail::Version.table_exists?
    => false
    PaperTrail::Version.octopus_establish_connection Octopus.config[Rails.env][:ms]
    PaperTrail::Version.table_exists?
    => true

Where and how can I put:

    PaperTrail::Version.octopus_establish_connection Octopus.config[Rails.env][:ms]

I tried to put it in `app/models/papertrail_version.rb` and in `config/initializers/papertrail.rb`, but in model is not loaded, and in initializers it fails because Octopus has not been bundled yet, I suppose I could bundle it in initializer, any advice on how to get this as simple as possible.

# Update

I tried in initializer with no luck:

    require 'octopus'
    PaperTrail::Version.octopus_establish_connection Octopus.config[Rails.env][:ms]

I am getting this when trying to run rails console:

    /vagrant/config/initializers/papertrail_version.rb:3:in 
    `<top (required)>': undefined method `[]' for nil:NilClass (NoMethodError)

# Update 2

In `app/models/paper_trail/version.rb`:

    module PaperTrail
      class Version < ActiveRecord::Base
        octopus_establish_connection Octopus.config[::Rails.env][:ms]
      end
    end

Note I had to use `::` in `Rails.env`

But when I go to console I get:

    [2] pry(main)> PaperTrail::Version.first
    ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "versions" does not exist
    LINE 5:              WHERE a.attrelid = '"versions"'::regclass
                                            ^

This means that is taking master DB, where table does not exist.

**Comment by sobrinho** [comment]
I need more information to track this down like rails version, octopus version and paper trail version.

Feel free to reopen if this is still an issue on latest release of octopus.
