### ISSUE TITLE
uninitialized constant Octopus::Logger

### ISSUE THREAD

**Issue by swapnilabnave** [tchandy/octopus#232]
Is this Wiki-page outdated ? - https://github.com/tchandy/octopus/wiki/Logger
When I run `$ rake octopus:copy_schema_versions`
I get the following error

```
rake aborted!
uninitialized constant Octopus::Logger
/home/swapnil/apps/sharding/config/initializers/octopus.rb:1:in `<top (required)>'
````
`config/initializers/octopus.rb` has:
```ruby
ActiveRecord::Base.logger = Octopus::Logger.new("#{Rails.root}/log/#{Rails.env}.log")
````

**Comment by tchandy** [comment]
Hi @swapnilabnave ,

Yes, it was an outdated page. The wiki was updated.

Thiago
