### ISSUE TITLE
Octopus.using not working on production/staging

### ISSUE THREAD

**Issue by swapnilabnave** [tchandy/octopus#234]
`Octopus.using` doesn't seem to work on Heroku staging environment. Per [octopus.rb](https://github.com/tchandy/octopus/blob/master/lib/octopus.rb#L87), connection should be of type `Octopus::Proxy` i.e. `conn.is_a?(Octopus::Proxy)` should be true but it returns false. 

I checked on console
**Development:**
```
2.0.0p195 :001 > conn = ActiveRecord::Base.connection;nil
 => nil 
2.0.0p195 :002 > conn.class
 => Octopus::Proxy 
```
**Staging:**
```
irb(main):003:0> conn = ActiveRecord::Base.connection;nil
=> nil
irb(main):005:0> conn.class
=> ActiveRecord::ConnectionAdapters::PostgreSQLAdapter
```
Hence it doesn't use the shard(slave).
Somewhat similar to https://github.com/tchandy/octopus/issues/82

> When restarting a dyno on heroku I can see these logs
```
2014-03-26T01:14:29.357474+00:00 app[web.2]: => 1 database enabled as read-only slave
2014-03-26T01:14:29.357562+00:00 app[web.2]:  * ROSE follower
```

I followed the wiki [Replication-with-Rails-on-Heroku](https://github.com/tchandy/octopus/wiki/Replication-with-Rails-on-Heroku)
* [config/initializers/octopus.rb](https://gist.github.com/swapnilabnave/9c0b1a34d15ac8c70157#file-config_initializers_octopus-rb)
* [config/shards.yml](https://gist.github.com/swapnilabnave/58f4c08dd24098cebfd7#file-shards-yml)

Also as said is the [wiki](https://github.com/tchandy/octopus/wiki/Replication-with-Rails-on-Heroku) I have used following HEAD
`gem "ar-octopus", github: "rocketmobile/octopus", require: "octopus"`

Any help, what extra *configs* do I need to make it work ?

**Comment by sobrinho** [comment]
Closing since it appears to be fixed on latest octopus release.

**Comment by JigarS91** [comment]
Hi There,

We are having issues with connecting to our replica database using Octopus. Issue is occurring on production and works completely fine on QA.

When we run command - Octopus.using(:replica1) { User.last }. We get below error: -

Octopus.using(:replica1) { User.last }
Mysql2::Error: Can't connect to MySQL server on 'XXXXXXXXXXXXXXXXXXXXXXX' (4)
	from /usr/local/bundle/gems/mysql2-0.3.18/lib/mysql2/client.rb:70:in `connect'
	from /usr/local/bundle/gems/mysql2-0.3.18/lib/mysql2/client.rb:70:in `initialize'
	from /usr/local/bundle/gems/activerecord-4.2.7/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `new'
	from /usr/local/bundle/gems/activerecord-4.2.7/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `mysql2_connection'
	from /usr/local/bundle/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
	from /usr/local/bundle/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
	from /usr/local/bundle/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
	from /usr/local/bundle/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
	from /usr/local/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	from /usr/local/bundle/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
	from /usr/local/bundle/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
	from /usr/local/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	from /usr/local/bundle/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
	from /usr/local/bundle/gems/ar-octopus-0.9.2/lib/octopus/proxy.rb:76:in `safe_connection'
	from /usr/local/bundle/gems/ar-octopus-0.9.2/lib/octopus/proxy.rb:80:in `select_connection'
	from /usr/local/bundle/gems/ar-octopus-0.9.2/lib/octopus/proxy.rb:25:in `quote_table_name'
... 7 levels...
	from /usr/local/bundle/gems/activerecord-4.2.7/lib/active_record/querying.rb:3:in `last'
	from (irb):1:in `block in irb_binding'
	from /usr/local/bundle/gems/ar-octopus-0.9.2/lib/octopus/proxy.rb:86:in `block (2 levels) in run_queries_on_shard'
	from /usr/local/bundle/gems/ar-octopus-0.9.2/lib/octopus/proxy.rb:324:in `using_shard'
	from /usr/local/bundle/gems/ar-octopus-0.9.2/lib/octopus/proxy.rb:85:in `block in run_queries_on_shard'
	from /usr/local/bundle/gems/ar-octopus-0.9.2/lib/octopus/proxy.rb:308:in `keeping_connection_proxy'
	from /usr/local/bundle/gems/ar-octopus-0.9.2/lib/octopus/proxy.rb:84:in `run_queries_on_shard'
	from /usr/local/bundle/gems/ar-octopus-0.9.2/lib/octopus.rb:144:in `using'
	from (irb):1
	from /usr/local/bundle/gems/railties-4.2.7/lib/rails/commands/console.rb:110:in `start'
	from /usr/local/bundle/gems/railties-4.2.7/lib/rails/commands/console.rb:9:in `start'
	from /usr/local/bundle/gems/railties-4.2.7/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /usr/local/bundle/gems/railties-4.2.7/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /usr/local/bundle/gems/railties-4.2.7/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:9:in `require'
	from bin/rails:9:in `<main>'

Mysql Version is same on both the databases as well as shards.yml is same.

Below is shards.yml config: -

<%
  require 'cgi'
  require 'uri'
  if ENV['DATABASE_REPLICA_URL'].present?
    config = {}
    replica_url = ENV['DATABASE_REPLICA_URL']
    uri = URI.parse(replica_url)
    config['host'] = uri.host
    config['username'] = uri.user
    config['password'] = uri.password
    config['database'] = (uri.path || '').split('/')[1]
  end
%>

octopus:
  replicated: false
  fully_replicated: false
  environments:
  <%- if config.present? %>
      <%= "- #{ENV["RAILS_ENV"] || ENV["RACK_ENV"] || Rails.env}" %>
  <%= ENV['RAILS_ENV'] || ENV['RACK_ENV'] || Rails.env %>:
    replica1:
      adapter: mysql2
      host: <%= config['host'] %>
      username: <%= config['username'] %>
      password: <%= config['password'] %>
      database: <%= config['database'] %>
      reconnect: true
      encoding: utf8mb4
  <% else %>
    - none
  <% end %>

Checked firewall and everything looks good. Unable to figure it out. Please assist.
