### ISSUE TITLE
Does Octopus run migrations on both master and slave shards?

### ISSUE THREAD

**Issue by sahanmalagi** [tchandy/octopus#237]
I found that after running a migration(for creating a table), The table was created only on the master but not replicated on the slave.

My setup is that I have a master and a slave both running Rails 3

When running a migration(for creating a new table), I used the 'using(:master)' directive in my migration with the understanding the after running the migration, The table will be created in the master but replicated by Octopus on the Slave. 

However, I see the table created on the Master but not replicated on the Slave.

Could someone tell me why Octopus is not replicating 'table creation' on the Slave Shard? Is it because I used the 'using(:master)' directive in my migration? How should I correct it?

Thanks much,

Sam

SHARDS.YML
==========

octopus:
  replicated: true
  fully_replicated: true
  environments:
    - development

  development:
    slave1:
      host: my_host
      adapter: mysql2
      database: my_db
      username: dev
      password: dev
      reconnect: true

**Comment by tchandy** [comment]
Hi @sahanmalagi ,

I think @mumoshu answer solved your problem. 

I'm closing this issue. If you have any additional problems, feel free to reopen.

Thiago
