### ISSUE TITLE
Master database got re-initialized

### ISSUE THREAD

**Issue by denishaskin** [tchandy/octopus#240]
I don't see how this could have been due to octopus, but I'll just ask here for completeness.

Our app is on heroku, with a follower.  I set up octopus and deployed.

Within a few minutes the master database was an empty schema.  As if `db:reset` had been run.

I had it set to `replicated: true` (`fully_replicated: false`), did not have any models configured with `replicated_model`.

There was this hiccups when I first deployed: The SLAVE_DISABLED_FOLLOWERS environment variable wasn't set at first deployment, and so at first it tried to include a database it shouldn't have. I set it and restarted all my dynos.

As I said, I am dubious as to how this could be related to Octopus, and unfortunately we don't have logs going far back enough (this was a staging environment). But I thought I would check if there's any possible relationship.

**Comment by tchandy** [comment]
Hi @denishaskin ,

I don't think your problem was related to Octopus. 

I'm closing this issue. If you have any additional problems, feel free to reopen.

Thiago
