### ISSUE TITLE
Not all select queries going to slaves

### ISSUE THREAD

**Issue by neilberget** [tchandy/octopus#244]
I have a fully replicated setup (c8a01d88 using Rails 4.0) and have noticed that many select queries are still going to master.

In troubleshooting, I've noticed that queries from methods run directly on an ActiveRecord model: 

    User.find(1)

will get properly routed to the slave, but relations do not:

    User.find(1).groups

will result in the query for the groups going straight to master. Curiously, adding an includes will result in all queries going to the slave:

    User.includes(:groups).find(1).groups

Also, explicitly setting the slave with a using works as expected as well:

    User.using(:slave1).find(1).groups

But if I understand correctly that should not be necessary in a fully replicated setup.

Any ideas? Thanks!

**Comment by jamesmeador** [comment]
An update on the status of this would be great. @tchandy progress?

**Comment by joelr** [comment]
still having this issue, anyone else got this resolved?

**Comment by jamesmeador** [comment]
I switched to makara.

On Monday, April 6, 2015, Joel Richards <notifications@github.com> wrote:

> still having this issue, anyone else got this resolved?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tchandy/octopus/issues/244#issuecomment-90403339>.
>


-- 
*James Meador*
Cell: (225)978-2911

**Comment by intouchmvc** [comment]
Very interested to hear how that works out for you. We use Octopus now but that was one I have kept an eye on….

 

Richard

**Comment by sobrinho** [comment]
Closing in favor of #245.

**Comment by jamesmeador** [comment]
> Very interested to hear how that works out for you. We use Octopus now but that was one I have kept an eye on….
> 
> Richard
> 
Hey Richard, any chance you can edit the cell phone number out of the above comment?

**Comment by sobrinho** [comment]
@jamesmeador edited for you.
