### ISSUE TITLE
HasAndBelongsToManyAssociation (NameError)

### ISSUE THREAD

**Issue by shopuz** [tchandy/octopus#249]
Hi I am getting the following error when I try to run the server. The bundle installed successfully though.
.rvm/gems/ruby-2.1.0/bundler/gems/octopus-1a123eadf98c/lib/octopus/has_and_belongs_to_many_association.rb:7:in `<top (required)>': uninitialized constant ActiveRecord::Associations::HasAndBelongsToManyAssociation (NameError)

Regards
Suren

**Comment by sobrinho** [comment]
This fix is already released, thanks!

**Comment by fanjieqi** [comment]
The error would be triggered when rails upgrade 5.0.0.
And I've watched the source code, and it should add a method naming "rails41_rails5?".
(English isn't my first language, I'm sorry for my grammar error.)
