### ISSUE TITLE
Replicate only if...

### ISSUE THREAD

**Issue by miriamdeana** [tchandy/octopus#253]
Is there a way to only replicate (update Slave) when a condition is met?

I have a Version model.  When it is updated, then and only then, the Slave should be updated to match the Master.

Updates to other models can be made by an user, but the Version will only be updated by a super_user who "approves" all changes made since last version update.

**Comment by tchandy** [comment]
Hi @miriamdeana ,

I assume that @mumoshu answer was enough to solve your problem. 

I'm going to close this issue. If you have other additional problems, please fell free to reopen.

Thiago
