### ISSUE TITLE
undefined method `>' for #<ActiveSupport::OrderedHash

### ISSUE THREAD

**Issue by rossi-jeff** [tchandy/octopus#255]
Like your gem, have an issue I thought I should bring to your attention. I looked briefly though issues and did not see it, sorry if I missed it. Getting an error when calling .size on query results if there was a join in the query.

The error:
Completed 500 Internal Server Error in 24.4ms

NoMethodError (undefined method `>' for #<ActiveSupport::OrderedHash:0x007f43e4e05428>):
  app/controllers/reports/driver_controller.rb:157:in `timecard'
  app/controllers/application_controller.rb:307:in `select_shard'

The relevant code:
	@trip_events = TripEvent.paginate(
	  :joins => "INNER JOIN trip_event_stats ON trip_event_stats.trip_event_id = trip_events.id",
  	  :conditions => ["trip_event_stats.driver_id=? and (trip_events.created_at between ? and ?) and (trip_events.suspect is null or trip_events.suspect=0)",@driver.id,@start_dt_str,@end_dt_str],
     :group => "trip_events.id",
     :order => "created_at desc",
     :per_page=>ResultCount,
     :page => @page
	)
	@stop_durations = {}
	if @trip_events.size > 0
		# omitted for brevity
	end
	

referenced method:
	def select_shard(&block)
     ActiveRecord::Base.custom_octopus_connection = false
     Octopus.using(:slave1, &block)
   end

**Comment by tchandy** [comment]
Hi @rossi-jeff ,

Any updates on this issue? Did you solved the problem or just disabled pagination?

Thiago

**Comment by rossi-jeff** [comment]
Thiago,

did a couple things.

instead of

Model.paginate()

used

Model.find().paginate()

and in several places needed

require ‘will_paginate/array’

Traced it back to an active record issue but I don’t have the info in front of me now.

Thank You,

Jeff

**Comment by sobrinho** [comment]
Closing due to lack of movement but I would be happy to inspect if this is still an issue for you. Please test against latest released version if that's the case.
