### ISSUE TITLE
RuntimeError: Nonexistent Shard Name: slave1

### ISSUE THREAD

**Issue by DanielZhangQingLong** [tchandy/octopus#259]
this is my config. 
octopus:
  replicated: true
  #environments:
  #  - development
  #  - production
  development:
    slave1:
      host: 159.226.67.89
      adapter: mysql2
      database: testmirror
      username: root
      password: root
  production:
    slave1:
      host: 159.226.67.89
      adapter: mysql2
      database: testmirror
      username: root
      password: root

and I got "RuntimeError: Nonexistent Shard Name: slave1" error. Do I have something wrong?

**Comment by tchandy** [comment]
Hi @DanielZhangQingLong ,

I hope that @mumoshu comments solved your problem.

I'm closing this issue, if you have any additional problems please feel free to reopen.

Thiago
