### ISSUE TITLE
Octopus breaks Squeel relation merge

### ISSUE THREAD

**Issue by HitmanInWis** [tchandy/octopus#260]
The squeel gem fails to merge ActiveRecords::Relations correctly when ar-octopus is included.  This is b/c ar-octopus wraps the ActiveRecords::Relation class with Octopus::RelationProxy, which squeel fails to recognize as an ActiveRecord::Relation.

The problematic code in squeel is in the Squeel::Adapters::ActiveRecord::RelationExtensions module.

    def relation_with_different_base?(r)
      ::ActiveRecord::Relation === r &&
      base_class.name != r.klass.base_class.name
    end

I was able to solve this problem with the following monkey patch

    module ActiveRecord
      class Relation
        class << self
          alias :old_self_equal :===
          def ===(obj)
            old_self_equal(obj) || ::Octopus::RelationProxy === obj
          end
        end
      end
    end

I am not sure if there are any negative repercussions of doing this, but it does fix the problem that we were running into.

Another approach I attempted was this

    module Octopus
      class RelationProxy
        def is_a?(klass)
          super(klass) || @ar_relation.is_a?(klass)
        end
      end
    end

I was thinking the "===" method for a class delegated to the "is_a?" method of the passed in object, but that apparently is not the case, so this did not solve the problem.

I'm not sure what the appropriate solution for this issue is, or whose fault the bug is (squeel or octopus) but posting this here in case anyone else runs into the problem.

**Comment by sobrinho** [comment]
Probably fixed by #269.

Feel free to reopen if this is still an issue.
