### ISSUE TITLE
stack level too deep with Kaminari

### ISSUE THREAD

**Issue by sr3d** [tchandy/octopus#265]
I'm using ar-octopus gem to handle switching databases at runtime but I started to have Stack level too deep error.

    stack level too deep

    Rails.root: /path/to/project

    Application Trace | Framework Trace | Full Trace
    actionpack (4.1.1) lib/action_dispatch/middleware/reloader.rb:79

After removing the ar-octopus gem from the Gemfile, the page works again.  I'm still digging but it leads to the total_count method in Kaminari.

**Comment by tchandy** [comment]
Hi @sr3d , 

Any updates on the Kaminari issue? 

Thiago

**Comment by sobrinho** [comment]
I believe it got fixed by #329.
