### ISSUE TITLE
Calling #load on Octopus::RelationProxy dispatches to Object#load

### ISSUE THREAD

**Issue by RocketPuppy** [tchandy/octopus#281]
Octopus::RelationProxy subclasses Object, which defines #load. The #method_missing implementation on Octopus::RelationProxy therefore doesn't get a chance to delegate to ActiveRecord::AssociationRelation, as the dispatch system dispatches to Object#load before calling Octopus::RelationProxy#method_missing.

**Comment by sobrinho** [comment]
Probably fixed by #269.

Feel free to reopen if this is still an issue.
