### ISSUE TITLE
Shard connection went down

### ISSUE THREAD

**Issue by mxposed** [tchandy/octopus#285]
I'm testing `octopus` with my app with master/slave replication and came across a strange behaviour. I have some controllers which work only with master and some controllers which work only with slave. I wrap them in `around_filters` with the corresponding `using` call.
If i start my app with slave mysql down all works as i expect: master controllers work, slave controllers don't. If i then start slave mysql, slave controllers start to work. However if i then stop slave mysql again, both controllers stop working.

I wonder why is it happening and are there any workarounds?

**Comment by sobrinho** [comment]
Octopus doesn't deal with slave failures yet, follow #323.
