### ISSUE TITLE
Replication database names

### ISSUE THREAD

**Issue by dvodvo** [tchandy/octopus#290]
Sorry if this seems banal, but the questions derives from a point where I fail to grasp the logic. And, all to often proper naming can mean a world of (non-)confusion.

Context: replication ONLY

Using your `octopus_replication_example` you defined the master database's name `database: octopus_replication_1` in database.yml
In `shards.yml`, each instance has its own database name, i.e. `database: octopus_replication_2`. It feels unnatural that on a replication basis only, i.e. these are read-only containers, that the database have a different name than its master (a true shard would NEED to have a distinguishing name)

I realise that the directive `octopus:
  replicated: true`
circumvents the matter, but, would naming the shards with the same name as the master have any consequence to operations?

**Comment by tchandy** [comment]
Hi @dvodvo ,

To be honest, I think it would generate an problem. Since Octopus uses shard names as keys, it might override a few of your shards, not sending queries to them.

I'm closing this issue. If you have any additional problems, please feel free to reopen.

Thiago
