### ISSUE TITLE
Issues in Rails console after starting to use Octopus

### ISSUE THREAD

**Issue by lsato** [tchandy/octopus#298]
We're on Rails 3.2.5 using Octopus 0.8.3, and we're having problems with running queries on our staging  console we weren't having before. We're sharding with Octopus, and we've got the shards stored in the database instead of having a configuration file with all of the information. We've also got a primary column for each Shard to decide which shard new data will be added to. If we were to change the primary shard through a rails console (ex: Shard.find(x).set_to_primary), it doesn't execute / it hangs, but once I kill the command and rerun it, it executes within a couple ms.

Anyone else having issues similar to this?

**Comment by tchandy** [comment]
Hi @lsato ,

Do you have more information about your issue? could you post a sample of your config file?

Thiago

**Comment by lsato** [comment]
I'm going to close this out - it seems like we're not having this problem on production - only on test environments
