### ISSUE TITLE
Update octopus version to 0.8.5 to roll out the broken touch fix.

### ISSUE THREAD

**Issue by s33m4nn** [tchandy/octopus#299]
I have to manually remove and install octopus 8.4 to apply adimitrov's Rails 4.2 broken touch fix (adimitrov on Dec 30, 2014 Update touch arguments, 9206f65). Please, update version information.

**Comment by tchandy** [comment]
Hi @s33m4nn , 

Just released Octopus 0.8.5. 

Thiago
