### ISSUE TITLE
Use case question

### ISSUE THREAD

**Issue by cheeseandpepper** [tchandy/octopus#300]
Is it possible to use octopus so that
  - All reads go to master
  - All writes go to master and slave

I want to keep a replicated and up to date database copy somewhere else where I can run frequent sql queries and not add load to master.  

Please let me know if it can be configured this way.

**Comment by tchandy** [comment]
I @cheeseandpepper ,

Octopus don't support it out of the box, but I think you could have an after_save callback to replicate your data to your slave databases using Octopus.

I'm closing this issue. If you have other additional problems, please fell free to reopen.

Thiago
