### ISSUE TITLE
ActiveRecord::ConnectionNotEstablished when using sidekiq workers

### ISSUE THREAD

**Issue by Geesu** [tchandy/octopus#310]
I'm currently running into a problem with Octopus `0.8.5`, sidekiq `3.3.0`, and rails `4.1.2`.  Basically my sidekiq worker constantly throws `ActiveRecord::ConnectionNotEstablished`.

How I'm configuring shards.yml: https://gist.github.com/Geesu/fb5aea940f569104402f

And the resulting info on the connection:
```[1] pry(main)> ActiveJob.connection.instance_eval{ @shards }['slave1'].instance_eval{@spec}
=> #<ActiveRecord::ConnectionAdapters::ConnectionSpecification:0x00000106f5af58
 @adapter_method="postgresql_connection",
 @config={"adapter"=>"postgresql", "database"=>"database", "username"=>"username", "password"=>"password", "host"=>"example.com", "pool"=>250, "reaping_frequency"=>60, "octopus_shard"=>"slave1"}>```

The stack trace: https://gist.github.com/Geesu/dc9ca283da3fba05c9e4

Any suggestions?

**Comment by Geesu** [comment]
Figured it out.  I needed to do the following in my `sidekiq.rb` initializer:

```Sidekiq.configure_server do |config|
  config.server_middleware do |chain|
    ActiveRecord::Base.connection.initialize_shards(Octopus.config)
  end
end```

**Comment by pratik60** [comment]
@Geesu I was getting a connection timeout error. Your code didn't help as such, could you also post the shards.yml configuration, anything else?

It seems that for the shards its taking 5 as the pool

**Comment by Geesu** [comment]
You can find it here: https://gist.github.com/Geesu/fb5aea940f569104402f

**Comment by pratik60** [comment]
@Geesu Stay with me...I have spent about 12 hours debugging, till I realized it was octopus that was creating the problem :-(

Gimme 2 minutes, would really appreciate your help

**Comment by pratik60** [comment]
Database.yml
```
staging:
  adapter: postgresql
  encoding: utf8
  database: adiq_staging
  pool: 100
  username: postgres
  host: xyz
  port: 5432
```

Shards.yml

octopus:
    replicated: true
    fully_replicated: true
    environments:
        - staging
    staging:
        read:
            host: localhost
            adapter: postgresql
            database: adiq_staging
            username: deploy
            password: password

Adding your code as it is in sidekiq.rb, but that didn't work for me....Any idea why that could be?

**Comment by pratik60** [comment]
Just added pool in shards.yml , and set it to 100, and voila! Feck, can't believe that long.... :-( :-) :-(


Total mix of emotions

**Comment by Geesu** [comment]
Glad you figured it out! We actually didn't end up implementing octopus so I wasn't sure I would have been much help :P
