### ISSUE TITLE
Problem with accessing rails session when using db store (Active record store.)

### ISSUE THREAD

**Issue by Nitin-Salunke** [tchandy/octopus#312]
I'm using octopus for database replication.
Only issue I'm having is that I'm not able to access the session values which I have set.

I feel that when writing into session, it is stored in master database and when reading it reads from the one of the slave database.

I wanna know if there is a way by which I can tell octopus to use master database for session read/write operations ?

**Comment by sobrinho** [comment]
Seems like 316 is fixing that, let's go to there.
