### ISSUE TITLE
Ruby 1.8.7 is not supporting octopus

### ISSUE THREAD

**Issue by bethink** [tchandy/octopus#314]
in https://github.com/tchandy/octopus/blob/master/lib/octopus/model.rb

     def hijack_methods
        around_save :run_on_shard, :unless => -> { self.class.custom_octopus_connection }
        after_initialize :set_current_shard

-> lambda syntax supports from ruby-1.9.0.
But in rubygems.org says, octopus supports >= 0 ruby verison.

**Comment by sobrinho** [comment]
Fixed by bc77ae3b342bb6af283c04629c4a28ba06995f2c
