### ISSUE TITLE
replicated_model is not working (on Heroku at least)

### ISSUE THREAD

**Issue by akitaonrails** [tchandy/octopus#317]
I am trying to have partial replication (writes to master, reads from follower). I've followed the exact documentation from here: https://devcenter.heroku.com/articles/distributing-reads-to-followers-with-octopus

I tried a bare bone 4.0 and 4.1 apps, downloaded the dynamic shards.yml and initializers/octopus.rb using both the stable gem and master branch in the Gemfile. I created a bare bone Heroku app with 2 free database not replicated from each other and inserted different rows to make sure where the queries are going to.

Adding `replicated_model` in the model definition is not working at all. Not even setting the instance variable by hand to true. Only forcing using the `Octopus.using` block works.

I can share the code but it's just a `rails _4.0.11_ new demo; cd demo; rails scaffold Page title:string` with the Octopus gem in the Gemfile and `replicated_model` directive in the Page class deployed to Heroku as explained. Nothing fancy.

`Page.first` should go to the non-primary database but it's not, it always goes to master. This is how running `Octopus.config` in heroku console looks like:

```
=> {"replicated"=>true, "fully_replicated"=>true, "environments"=>["production"], "production"=>{"followers"=>{"mauve_follower"=>{"adapter"=>"postgresql", "database"=>"dedavjngq3qkoj", "username"=>"ymdiwpekgzxavb", "password"=>"IFeXrDmU8BucVzfUxevm7hLM8D", "host"=>"ec2-54-204-27-193.compute-1.amazonaws.com", "port"=>5432}}}}
```

Looks ok, it is fetching the correct secondary database. But it's simply not rerouting the reads to it. Anyone ever saw this?

**Comment by carloslopes** [comment]
This error is happening since version 0.8.2. 
`replicated_model`s are working correctly on version 0.8.1

I investigate the cause and try to send a PR

**Comment by akitaonrails** [comment]
Wow, v0.8.1 to v0.8.2 changes a whole lot: https://github.com/tchandy/octopus/compare/v0.8.1...v0.8.2
Impossible to track what broke. 0.8.2 could easily be a 0.9.0 release :-)

**Comment by carloslopes** [comment]
Doing a bisect, it appears that the commit that introduced the bug is: 0cd1d28743c1fd87ff801ce6fb021322b0cc66e3

I'm taking a look to find the cause.

**Comment by sobrinho** [comment]
I'm trying to replicate it right now.

**Comment by sobrinho** [comment]
Well, I've requested support from Heroku to edit the article because it's incomplete (wrong).

You should use this template:

``` yaml
<%
require 'cgi'
require 'uri'

def attribute(name, value, force_string = false)
  if value
    value_string =
      if force_string
        '"' + value + '"'
      else
        value
      end
    "#{name}: #{value_string}"
  else
    ""
  end
end

configs = case Rails.env
when 'development', 'test'
  # use dev and test DB as feaux 'follower'
  Array.new(2){YAML::load_file(File.open("config/database.yml"))[Rails.env]}
else
  # staging, production, etc with Heroku config vars for follower DBs
  master_url = ENV['DATABASE_URL']
  slave_keys = ENV.keys.select{|k| k =~ /HEROKU_POSTGRESQL_.*_URL/}
  slave_keys.delete_if{ |k| ENV[k] == master_url }

  slave_keys.map do |env_key|
    config = {}
    begin
      uri = URI.parse(ENV["#{env_key}"])
    rescue URI::InvalidURIError
      raise "Invalid DATABASE_URL"
    end

    raise "No RACK_ENV or RAILS_ENV found" unless ENV["RAILS_ENV"] || ENV["RACK_ENV"]
    config['color'] = env_key.match(/HEROKU_POSTGRESQL_(.*)_URL/)[1].downcase
    config['adapter'] = uri.scheme
    config['adapter'] = "postgresql" if config['adapter'] == "postgres"

    config['database'] = (uri.path || "").split("/")[1]

    config['username'] = uri.user
    config['password'] = uri.password

    config['host'] = uri.host
    config['port'] = uri.port

    config['params'] = CGI.parse(uri.query || "")
    config
  end
end

whitelist = ENV['SLAVE_ENABLED_FOLLOWERS'].downcase.split(', ') rescue nil
blacklist = ENV['SLAVE_DISABLED_FOLLOWERS'].downcase.split(', ') rescue nil

configs.delete_if do |c|
  ( whitelist && !c['color'].in?(whitelist) ) || ( blacklist && c['color'].in?(blacklist) )
end
%>
octopus:
  replicated: true
  fully_replicated: false
  environments:
  <% if configs.present? %>
    <%= "- #{ENV["RAILS_ENV"] || ENV["RACK_ENV"] || Rails.env}" %>
  <%= ENV["RAILS_ENV"] || ENV["RACK_ENV"] || Rails.env %>:
    <% configs.each_with_index do |c, i| %>
    <%= c.has_key?('color') ? "#{c['color']}_follower" : "follower_#{i + 1}" %>:
      <%= attribute "adapter",  c['adapter'] %>
      <%= attribute "database", c['database'] %>
      <%= attribute "username", c['username'] %>
      <%= attribute "password", c['password'], true %>
      <%= attribute "host",     c['host'] %>
      <%= attribute "port",     c['port'] %>
      <% (c['params'] || {}).each do |key, value| %>
      <%= key %>: <%= value.first %>
      <% end %>

    <% end %>
  <% else %>
    - none
  <% end %>
```

The different is that I removed the `followers` key before the followers, it is used to create slave groups which requires you to explicit use `Octopus.using(slave_group: :followers)` but it's not necessary on most applications.

See #239 which introduced this feature.

**Comment by sobrinho** [comment]
Also you should remove `config/initializers/octopus.rb` which is suggested by the heroku article because it's not necessary and it's broken for application without slave groups.

**Comment by carloslopes** [comment]
Hmm thank you @sobrinho !

I moved to another city so it was complicated to me take a look at this, I will update my application
