### ISSUE TITLE
Current shard is reverts to master unnecessarily

### ISSUE THREAD

**Issue by atombender** [tchandy/octopus#36]
Consider the following code:

    g = Group.find(9)
    Octopus.using(:slave1) do
      g.members.count  # (1) This reads from master, not the slave
      Group.find(8)  # (2) This also reads from master, not the slave
    end

I have traced Octopus a little bit and this comes down to `reload_connection` being called on the model whenever an association is accessed.

I hope this is not by design, because it pretty much invalidates the use of Octopus for fine-grained load-balancing of read-only slaves. It looks like Octopus wants models to remember which shard they came from; that's fine if that "pinning" only applies to that actual model (although in my case I would like for case 1 to also read from the slave), but it reverts the connection for _all_ models and _all_ subsequent access within the `using` block.

In my opinion both (1) and (2) are bugs, but I can accept the behaviour in (1); ideally I would like an option to have it behave the way I like, however.

Background: We use Postgres 9.0 streaming replication, but due to the replication lag, only certain page components may be rendered using slave queries. So we want to wrap certain blocks with `Octopus.using`. Those page components necessarily refer to objects outside their scope; for example, there's a global, per-thread `current_user` context.

**Comment by sobrinho** [comment]
Closing due to lack of movement but I would be happy to inspect if this is still an issue for you. Please test against latest released version if that's the case.
