### ISSUE TITLE
Suggested way to handle read latency?

### ISSUE THREAD

**Issue by KensoDev** [tchandy/octopus#68]
Hey,

Using the gem in Amazon RDS.
When Amazon RDS sets up a read slave, there are times when you have 1 minute of replication latency.

Even though 1 minute is a rare case, 10 seconds latencies happen a few times a day.

From looking and the source code, this is obviously not handles, so I am thinking about implementing a `Dirty` kind of flag, so when the flag is true, you also read from the master.

Opinions? Advice?

**Comment by dreyks** [comment]
Is there any advancement in this feature?

**Comment by sobrinho** [comment]
I recently did a research about that and there is multiple ways to solve that.

If you need to handle the delay only for the current user, you could use redis to store the last write like `"user:#{user.id}:last_write" => Time.current` (as @KensoDev suggested).

And using a around filter you could use a threshold like this:

``` ruby
around_filter :handle_master_slave

def handle_master_slave
  last_write = Time.parse(Redis.get("user:#{user.id}:last_write"))
  threshold = 5.minutes # Tune to an appropriate threshold

  if Time.current + threshold < last_write
    Octopus.using(:master, &block)
  else
    Octopus.using(:slave, &block)
  end
end
```

There is a lot of other options like do that only for specific tables, objects, all users and etc. You must analyse your case to chose the appropriated solution.

I'm planning to write a wiki page about that ASAP.
